### ISSUE TITLE
Change the cursor direction upon language change

### ISSUE THREAD

**Issue by Sshuichi** [driftyco/ionic-plugin-keyboard#136]
if the language is RTL or LTR change the cursor. 
There are few RTL languages so maybe you can iterate on them and let the default LTR

**Comment by Ionitron** [comment]
Greetings @Sshuichi!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by jourdan-jobox** [comment]
Hello Ionic team,

I'd love to have RTL support for this Keyboard plugin! Has anyone come up with a way to start text input on the right side in order to support RTL, based on the User's Keyboard language?
