### ISSUE TITLE
keyboardhide and keyboardshow triggered when moving focus from input-to-input

### ISSUE THREAD

**Issue by brumm** [driftyco/ionic-plugin-keyboard#146]
both `native.keyboardhide` and `native.keyboardshow` are triggered if the user is tapping from-input-to-input, and the keyboard is not actually hidden and shown.

in our app, we do some fairly expensive dom manipulation and scrolling logic on `native.keyboardshow` which we'd like to avoid if the keyboard visibility hasn't actually changed.

related SO answer/workaround:
http://stackoverflow.com/questions/32595423/ios-9-uitextfield-textrectforbounds-issue/32638814#32638814

**Comment by Ionitron** [comment]
Greetings @brumm!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
