### ISSUE TITLE
disableScroll not working anymore

### ISSUE THREAD

**Issue by TobiasFriberg** [driftyco/ionic-plugin-keyboard#152]
Hey!

Seems like disableScroll isnt working with this new version. Updated Cordova and keyboard plugin to the newest versions.

**Comment by tlancina** [comment]
Hmm I'm unable to reproduce, what version of cordova, iOS and keyboard plugin?

**Comment by TobiasFriberg** [comment]
newest cordova, io9, and newest keyboard. Solved the problem with another solution and left the project. I was just thinking you guys would like to know about it and investigate it.

**Comment by mjaverto** [comment]
@TobiasFriberg what solution?

**Comment by TobiasFriberg** [comment]
@mjaverto I just didnt use the disableScroll and reworked the design.. Not important.

**Comment by gyoong2** [comment]
This is an issue for me.

Cordova v5.4.1
iOS 9.1
1.0.8 version of Keyboard Plugin

**Comment by tlancina** [comment]
![image](https://cloud.githubusercontent.com/assets/804331/11693540/0ba272e4-9e6b-11e5-93c6-3bf1e4695865.png)

It's working fine for me, are you calling `cordova.plugins.Keyboard.disableScroll(true)`? What makes you believe it isn't working?

**Comment by AdrianTeh** [comment]
@tlancina not working for me as well. When focused on an input field, keyboard showing up should not scroll the view, but it still does. Tested on ios9 emulator.

```
import {Keyboard} from 'ionic-native'

@Page({
  templateUrl: 'build/pages/login/login.html',
})
export class LoginPage {
  constructor(private nav: NavController, private platform: Platform) {
    this.platform.ready().then(() => {
      Keyboard.disableScroll(true);
    });
  }
}
```

#### Plugin information:

"name": "ionic-plugin-keyboard",
"version": "2.0.1",

#### My system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by finster** [comment]
I'm also having issues using the updated "ionic-plugin-keyboard" plugin (version 2.0.1) on ionic v1.2.4.

I'm using `cordova.plugins.Keyboard.disableScroll(true); `inside `$ionicPlatform.ready` but it doesn't seem to have any effect - my textarea is scrolling up to behind the top nav-bar (and sometimes off the top of the screen).

I don't think that this was happening on the previous version of the keyboard plugin.

Any help/workarounds would be great.

**Comment by tlancina** [comment]
I think there might possibly be some confusion as to what `disableScroll` does, and reading the docs just now I realize why.  I've just updated the README to hopefully be a LOT clearer.

`disableScroll` prevents the native UIScrollView from scrolling when an input is focused, meaning the entire screen shifts up.  The classic sign of this happening is your header bar disappears upwards.

However, it doesn't prevent any scrollable elements in the DOM within the UIWebView (the browser) from scrolling.  That needs to be handled with CSS and JavaScript, not this plugin.

If it's hard to visualize what's going on, think of an iframe in the middle of a page.  The iframe is scrollable, but the outer window doesn't move.  You can also scroll the outer window and the entire page moves.  The UIScrollView is like the outer window and your app is like an iframe that takes up the entire screen.  This plugin disables the entire screen from moving, but doesn't prevent scrollable elements in your app from doing their thing.

I'd also like to revisit the method names in an upcoming version, and I think `disableScroll` could be a lot more informative.  What do you guys think of `disableNativeScroll`? I'm not a huge fan of that either because Ionic uses the term 'native scroll' to describe CSS scrolling (vs. using JavaScript to scroll), but I think it would at least be slightly more clear than it is now.

Hope that clears things up! Going to close as I'm still unable to reproduce this, but I'm happy to re-open if there is a valid reproduction.

**Comment by finster** [comment]
OK, thanks for the info, that makes more sense now. I've updated my app to dynamically change the height of my textarea depending on screen resolution which works around my issue.
