### ISSUE TITLE
provide beforeShow and beforeClose callbacks.

### ISSUE THREAD

**Issue by Hirbod** [driftyco/ionic-plugin-keyboard#51]
Hi,

please provide a beforeShow and beforeClose event - sometimes it's just not enough to do some actions after the keyboard was shown/hidden.

Thanks!

**Comment by GitRubb** [comment]
+1
This is needed if using Disable/Enable scroll functionality

**Comment by tlancina** [comment]
Hey is this for Android? At the moment there is no real way to detect if the keyboard "will show" natively, but you can assume that a focus event is essentially the same thing.  Unfortunately you can't know what the keyboard height will be (but you could guess based on previous heights).

On iOS this is essentially what is already done, since keyboardshow fires on a KeyboardWillShow notification.
