### ISSUE TITLE
Why does hideKeyboardAccessoryBar() default to true?

### ISSUE THREAD

**Issue by jorisw** [driftyco/ionic-plugin-keyboard#97]
Hi,

Took me a while to find out that the keyboard plug-in won't show the accessory bar (for tabbing through input fields) because I needed to explicity set `cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false)`.

May I ask why this defaults to being hidden? It's a vital part of UX when showing a login form for example.

**Comment by jorisw** [comment]
... realising now that you probably didn't write that plugin, could ionic perhaps set it to be shown, by default? :)

**Comment by tlancina** [comment]
Hey there, the decision to remove it by default in the starter projects is because native apps don't have an accessory bar.  But yes, this can be somewhat of a gotcha!  We're considering having them commented out to start, so if people need common functionality (e.g. disableScroll or hideKeyboardAccessoryBar) it would be easy to find.  Thanks for the feedback!
