### ISSUE TITLE
Not working with WKWebView

### ISSUE THREAD

**Issue by etiennea** [driftyco/ionic-plugin-keyboard#98]
I know this is not key, considering the performance of WKWebView would be nice to have

**Comment by chaffeqa** [comment]
I actually would suggest ditching the ionic keyboard plugin for iOS when using the WKWebView.

I also suggest defaulting to native scrolling so that iOS has full control over the functioning of the keyboard + scrolling logic.

I have tested this and the native functionality works great.

I *would* suggest that you enable native scrolling by default, which allows for iOS to correctly calculate and control input logic.

    $ionicConfigProvider.scrolling.jsScrolling(false);

Also track this pull: https://github.com/driftyco/ionic/pull/3894

**Comment by danlg** [comment]
@chaffeqa  I've just ditched  ionic keyboard plugin for iOS when using the WKWebView with meteor 1.3 (which by default uses WKWebView) and the keyboard is now missing when I go onto fields.
I have basically replaced in a fork of meteor-ionic, all occurence of `Meteor.isCordova`  by `Meteor.isCordova && Platform.isAndroid()` in files ` ionFocus.js `and `ionKeyboard.js`. I need to keep  it for Android though so cannot get rid of 

Am I doing something wrong ? How do you actually "ditch"   ionic keyboard plugin for iOS using the WKWebView?

![image](https://cloud.githubusercontent.com/assets/12525045/14878676/9912d686-0d57-11e6-9bc2-b699da32d954.png)

**Comment by chaffeqa** [comment]
Basically took the DSL of the ionic plugin (*iOS only*) and either stubbed the methods that are no longer usable or replaced them with the [WKWebview cordova version](https://github.com/apache/cordova-plugins#master:keyboard).

You can see / use the fork we created: [here](https://github.com/sportstech/ionic-plugin-keyboard)

**Comment by danlg** [comment]
@chaffeqa  thanks a lot for the tip. What do you mean by DSL ? I've tried to use your fork of `ionic-plugin-keyboard` but it still doesn't work. In `meteor-ionic`, `package.js`, I've replaced in 

```
Cordova.depends({
  //'ionic-plugin-keyboard': '1.0.8'
  'ionic-plugin-keyboard': 'https://github.com/sportstech/ionic-plugin-keyboard/tarball/a75c589918638ebf87e48f2fe6eca3feb715133e'
});
```
![image](https://cloud.githubusercontent.com/assets/12525045/14934702/d2f7955e-0eeb-11e6-93b1-dc3b02ff8f50.png)
